# Generated by Django 3.1.3 on 2020-12-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('New order', 'New order'), ('Not delivered', 'Not delivered'), ('In process', 'In process'), ('Delivered', 'Delivered')], default='New order', max_length=20),
        ),
    ]
